### ISSUE TITLE
yargs-parser vulnerability 

### ISSUE THREAD

**Issue by AnshuTrivedi** [AnshuTrivedi/P1_People_Counter_APP#4]
1 yargs-parser vulnerability found in …/ui/package-lock.json.
I think upgrading yargs-parser to version 13.1.2 or later may solve issue. For example:
"dependencies": {
  "yargs-parser": ">=13.1.2"
}

**Comment by trivediavinash** [comment]
@AnshuTrivedi  hey i would  like to work on this ,could you pls assign this to me ?

**Comment by trivediavinash** [comment]
@AnshuTrivedi  are you referring [this](https://github.com/AnshuTrivedi/P1_People_Counter_APP/blob/e97276cc60dae17bd4cc901b0d7645df8b25064b/webservice/ui/package-lock.json#L12808)  ?

**Comment by AnshuTrivedi** [comment]
Yes @trivediavinash . Let me know if have any issue in making changes.
