### ISSUE TITLE
mongodb package update

### ISSUE THREAD

**Issue by AnshuTrivedi** [AnshuTrivedi/P1_People_Counter_APP#6]
mongodb vulnerability found in …/server/package-lock.json. 
Remediation
Upgrade mongodb to version 3.1.13 or later. For example:

"dependencies": {
  "mongodb": ">=3.1.13"
}

**Comment by ShubhamSood1406** [comment]
I can do this, I have to update the version of MongoDB?

**Comment by AnshuTrivedi** [comment]
@ShubhamSood1406  thanks for contribution.
Yes, you have to update version of MongoDB in package_lock.json file.

**Comment by ShubhamSood1406** [comment]
![image](https://user-images.githubusercontent.com/41718296/94348088-34079900-0057-11eb-9104-ae81ecf4a45e.png)
Just confirming, do I have to update the version of this MongoDB, as others MongoDB are the requirement of other dependencies.

**Comment by AnshuTrivedi** [comment]
@ShubhamSood1406  seems right. [confirm here](https://github.com/AnshuTrivedi/P1_People_Counter_APP/blob/e97276cc60dae17bd4cc901b0d7645df8b25064b/webservice/server/package-lock.json#L1918)

**Comment by ShubhamSood1406** [comment]
I updated the MongoDB version to 3.6.0, is that fine if I make a PR on 1st October.

**Comment by AnshuTrivedi** [comment]
Sure @ShubhamSood1406 . Best wishes for hacktoberfest.
